### ISSUE TITLE
split api.data.gov from data.gov

### ISSUE THREAD

**Issue by afeld** [18F/bug-bounty#39]
## Background Information

Right now, the [groups](https://hackerone.com/tts/groups) are both under data.gov. Since they are separate FISMA systems with separate teams, probably makes sense to split them apart in HackerOne.

## Implementation Steps

- [x] Create new group
- [x] Move users — just @gbinal and @gui I think
- [x] Notify HackerOne — not actually sure how they know which group to route to

## Acceptance Criteria

- [x] It's possible to triage issues to the api.data.gov team independently of the data.gov team

**Comment by its-a-lisa-at-work** [comment]
Brought this up at today's meeting and Sitora is going to look into it and get back to us.

**Comment by its-a-lisa-at-work** [comment]
Sent an email to HackerOne today nudging them on this

**Comment by its-a-lisa-at-work** [comment]
From H1:

We have a new user group created for api.data.gov, and triage has the following instructions: 

> For reports on api.data.gov, please assign to the api.data.gov group, as it's a different team than data.gov.


We already had api.data.gov as a separate scope item, and I separated it from the data.gov description in the policy:
