### ISSUE TITLE
HackerOne TTS & GSA integration

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/bug-bounty#41]
## Implementation Steps
- [x] Notify GSA that we're interested in understanding their efforts
- [x] Figure out costs
- [x] Figure out timelines

## Acceptance Criteria

- [x] Documented path forward with how to proceed with merging the two programs

**Comment by its-a-lisa-at-work** [comment]
Provided GSA IT Security asked for the following information:
- [x] breakdown of costs for maintaining the TTS program 
- [x] as well as any metrics on the number of findings reported

Got that started in the document for the [Bug Bounty Options ](https://docs.google.com/spreadsheets/d/1z0LtH56Z_4GHqm9hALf47RmopBYQZMzrRe2wBExm0DI/edit#gid=0)

Will update the document with
- [x] monthly bounty costs
- [x] refine the metrics on the findings per asset

**Comment by its-a-lisa-at-work** [comment]
Heard back from GSA IT Security 

> I spoke to Armando and unfortunately there is no money in his budget that can be used to support the current TTS applications/program until FY22. 
> 
> Hopefully we can work together to establish a transition plan to combine the programs for an efficient consolidation at that time. 
> 
> Please let me know if there is anything I can do to help in the meantime.
> 
> Thanks!

Creating a new card Bug Bounty Transfer to GSA IT Security 18F/tts-tech-portfolio#1224
